# Generated by Django 4.2.4 on 2023-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='Product'),
        ),
    ]
